In [1]:
import sys
sys.path.append("/Users/leo/projects/generalization_lipschitz")

In [2]:
from robustness.split_partitions import *

In [3]:
import torch
import torchvision

In [4]:
train_dataset = torchvision.datasets.CIFAR10(root="cifar_train", train=True,
                                      transform=torchvision.transforms.Compose(
                                          [
                                              torchvision.transforms.RandomHorizontalFlip(),
                                              torchvision.transforms.ToTensor()
                                          ]
                                      ),
                                       download=True
                                      )

Files already downloaded and verified


In [5]:
val_dataset = torchvision.datasets.CIFAR10(root="cifar_val", train=False,
                                      transform=torchvision.transforms.Compose(
                                          [
                                              torchvision.transforms.RandomHorizontalFlip(),
                                              torchvision.transforms.ToTensor()
                                          ]
                                      ),
                                       download=True
                                      )

Files already downloaded and verified


In [6]:
centroids = select_partition_centroid(100, train_dataset)

In [7]:
indices = assign_partition(val_dataset, centroids)
train_indices = assign_partition(train_dataset, centroids)

In [8]:
model_checkpoint = torch.load("model_best.pth.tar", map_location="cpu")

In [9]:
from model._mlp import _mlp

In [10]:
model = _mlp(in_features=3*32*32, cfg=[1024, 512, 256, 64], norm_layer=None, num_classes=10)

In [11]:
model.load_state_dict(model_checkpoint['state_dict'])

<All keys matched successfully>

In [12]:
calculate_robustness(model=model, train_dataset=train_dataset, test_dataset=val_dataset, train_indices = train_indices, test_indices=indices, loss_func=torch.nn.CrossEntropyLoss(reduction='none'))

tensor([5.9604e-06]) tensor([10.8733])
tensor([[15, 36]])
tensor([10.8733])
tensor([5.9604e-06])
tensor([0.0002]) tensor([3.1638])
tensor([7.4145e-05]) tensor([5.5116])
tensor([1.1921e-07]) tensor([12.4801])
tensor([[ 470, 1710],
        [ 470, 2082]])
tensor([12.4801])
tensor([1.1921e-07])
tensor([2.1100e-05]) tensor([8.7679])
tensor([0.0002]) tensor([1.8038])
tensor([0.0001]) tensor([6.5634])
tensor([0.0005]) tensor([4.7987])
tensor([1.1921e-07]) tensor([10.6401])
tensor([6.5325e-05]) tensor([4.3303])
tensor([4.7684e-07]) tensor([2.3453])
tensor([8.3446e-07]) tensor([6.1895])
tensor([0.0022]) tensor([4.2186])
tensor([0.0004]) tensor([5.4454])
tensor([1.1921e-07]) tensor([9.2638])
tensor([2.2888e-05]) tensor([8.7432])
tensor([0.0003]) tensor([2.6852])
tensor([0.0010]) tensor([2.4453])
tensor([-0.]) tensor([11.8933])
tensor([0.0002]) tensor([1.7808])
tensor([0.0025]) tensor([2.3387])
tensor([-0.]) tensor([8.0268])
tensor([3.9696e-05]) tensor([6.0650])
tensor([-0.]) tensor([6.7844])
ten

16.507614135742188