In [1]:
import sys
sys.path.append("/Users/leo/projects/gen_lipschitz/")

In [2]:
import torch

from train import start_train
from argparse import Namespace
from model.modified_layer import ModifiedAdaptiveAvgPool2d, ModifiedConv2d, ModifiedAdaptiveAvgPool2d, ModifiedMaxPool2d, ModifiedLinear

In [3]:
resnet_group_norm = {
    "model": "resnet34",
    "model_type": 2,
    "norm_type": "BN",
    "clamp_value": -1,
    "from_checkpoint": False
}
args = Namespace(**resnet_group_norm)
config, training_config = start_train(args, True)

In [4]:
model = training_config['model']

In [5]:
model

ResNet(
  (conv1): ModifiedConv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): ModifiedMaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): ModifiedConv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): ModifiedConv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): ModifiedConv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=T

In [6]:
variance = torch.load("/Users/leo/Downloads/variance_39_699.pth", map_location="cpu")

In [7]:
len(variance)

39

In [8]:
from model.modified_layer import *

In [11]:
count_modified_layer = 0
for layer in model.modules():
    if isinstance(layer, ModifiedConv2d) or isinstance(layer, ModifiedLinear) or \
            isinstance(layer, ModifiedAdaptiveAvgPool2d) or isinstance(layer, ModifiedMaxPool2d):
        count_modified_layer += 1
        continue
    if isinstance(layer, torch.nn.BatchNorm2d):
        try:
            gamma = layer.weight
            variance_temp = variance[count_modified_layer-1]
        except:
            print(count_modified_layer)
        print(gamma)
        print(variance_temp)

Parameter containing:
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], requires_grad=True)
tensor([0.9508, 0.5908, 0.8632, 0.8675, 0.8154, 0.5894, 1.1752, 1.3660, 1.3975,
        0.8924, 1.7650, 1.3887, 1.5091, 0.8463, 1.4455, 1.2623, 1.0135, 0.9409,
        0.9654, 2.3056, 1.0267, 0.8246, 1.2539, 1.1321, 1.4508, 1.0078, 0.9832,
        1.3841, 0.9360, 1.4645, 1.8292, 0.5099, 0.9273, 0.9515, 0.8790, 1.6823,
        1.1558, 1.3679, 1.2159, 0.4455, 0.7312, 1.7139, 0.7033, 1.6288, 0.9226,
        0.6939, 1.1641, 1.7615, 1.6717, 1.5011, 1.6211, 0.7676, 7.9981, 1.1738,
        1.6163, 1.7005, 1.7477, 1.1647, 1.3278, 0.7763, 0.6183, 1.9389, 0.6829,
        1.4822])
Parameter containing:
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.